# Only used for testing purposes
services:
  tools:
    image: amazon/aws-cli:latest
    container_name: my-collections-data
    tty: true
    command: sleep infinity
    volumes:
      - ./:/host/code
      - c:/tmp:/host/tmp
    environment:
      - TZ=UTC
    entrypoint: ["/bin/sh", "-c", "yum install -y dos2unix java-17-amazon-corretto tar unzip which && echo \"alias ll='ls -l'\" >> /etc/profile && sleep infinity"]