cts.andQuery([
  cts.jsonPropertyValueQuery(
    'dataType',
    ['DigitalObject', 'HumanMadeObject'],
    ['exact'],
  ),
  cts.orQuery([
    cts.tripleRangeQuery(
      [],
      [la('member_of')],
      fn.insertBefore(
        cts.values(
          cts.iriReference(),
          '',
          ['eager', 'concurrent'],
          cts.andQuery([
            cts.jsonPropertyValueQuery('dataType', ['Set'], ['exact']),
            cts.tripleRangeQuery(
              [],
              [lux('agentOfCuration')],
              fn.insertBefore(
                cts.values(
                  cts.iriReference(),
                  '',
                  ['eager', 'concurrent'],
                  cts.documentQuery([
                    'https://lux.collections.yale.edu/data/group/0a5ed086-396b-4cc2-8120-fdc3f8953ce2',
                  ]),
                ),
                0,
                sem.iri('/does/not/exist'),
              ),
              '=',
              [],
              1,
            ),
          ]),
        ),
        0,
        sem.iri('/does/not/exist'),
      ),
      '=',
      [],
      1,
    ),
    cts.tripleRangeQuery(
      [],
      [la('member_of')],
      fn.insertBefore(
        cts.values(
          cts.iriReference(),
          '',
          ['eager', 'concurrent'],
          cts.andQuery([
            cts.jsonPropertyValueQuery('dataType', ['Set'], ['exact']),
            cts.tripleRangeQuery(
              [],
              [lux('agentOfCuration')],
              fn.insertBefore(
                cts.values(
                  cts.iriReference(),
                  '',
                  ['eager', 'concurrent'],
                  cts.fieldValueQuery(
                    ['agentMemberOfId'],
                    [
                      'https://lux.collections.yale.edu/data/group/0a5ed086-396b-4cc2-8120-fdc3f8953ce2',
                    ],
                    ['exact'],
                    1,
                  ),
                ),
                0,
                sem.iri('/does/not/exist'),
              ),
              '=',
              [],
              1,
            ),
          ]),
        ),
        0,
        sem.iri('/does/not/exist'),
      ),
      '=',
      [],
      1,
    ),
  ]),
]);
