/*
 * THIS FILE IS PARTIALLY GENERATED BY THE BUILD SCRIPT.
 * IF EDITING, MAKE SURE YOU ARE EDITING THE SOURCE.
 *
 * Generated timestamp: Fri Feb 28 09:19:30 EST 2025
 */
const execute_with_lux = (f) => {
  return f();
};
const execute_with_lux_ipch = (f) => {
  return f();
};
const execute_with_lux_ypm = (f) => {
  return f();
};

export { execute_with_lux_ypm, execute_with_lux_ipch, execute_with_lux };
