/*
 * THIS FILE IS PARTIALLY GENERATED BY THE BUILD SCRIPT.
 * IF EDITING, MAKE SURE YOU ARE EDITING THE SOURCE.
 *
 * Generated timestamp: <%= timestamp %>
 */
import { EndpointConfig } from '../ml-modules/root/lib/EndpointConfig.mjs';
import { InternalConfigurationError } from '../ml-modules/root/lib/mlErrorsLib.mjs';
import { isUndefined } from '../ml-modules/root/utils/utils.mjs';

const ENDPOINTS_CONFIG = {
  // <%= topLevelObjects %>
};

function getCurrentEndpointPath() {
  return xdmp.getRequestPath();
}

function getCurrentEndpointConfig() {
  const endpointConfig = ENDPOINTS_CONFIG[getCurrentEndpointPath()];
  if (isUndefined(endpointConfig)) {
    throw new InternalConfigurationError(
      `The ${getCurrentEndpointPath()} endpoint is not configured.`
    );
  }
  return new EndpointConfig(endpointConfig);
}

export { getCurrentEndpointConfig, getCurrentEndpointPath };
