/*
 * THIS FILE IS PARTIALLY GENERATED BY THE BUILD SCRIPT.
 * IF EDITING, MAKE SURE YOU ARE EDITING THE SOURCE.
 *
 * Generated timestamp: <%= timestamp %>
 */

// Used by router function.
import { BadRequestError } from './mlErrorsLib.mjs';

// <%= functionLines %>

// <%= routerFunction %>

// <%= exportLines %>
